[package]
name = "ipc_demo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
env_logger = "0.11.8"
log = "0.4"
wxdragon = { path = "../../../rust/wxdragon" }

[build-dependencies]
embed-manifest = "1.4"
